Repository hpi-swa-teaching/OhmPrettyPrint, pull requests merged in 2020-08, with the labels that each got.

#112 Nil Values behandeln
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/BinaryMessageSend.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/FinalStatement.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
Labels: refactoring

#114 Installationsanleitung korrigieren
  README.md
Labels: bug

#111 firstChild eingebunden
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/FinalStatement.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/KeywordMessageSend.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/spaceBeforeCode.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
Labels: refactoring

#119 Code Duplication in arrayLiteralArray beheben
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/LiteralArrayLiteral.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/LiteralArrayLiteralInLiteralArray.with.and.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/literalArrayWith..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
Labels: refactoring

#127 Ändert == in = um
  packages/OmegaPrint-Core.package/CodeHolder.extension/instance/isShowingOmegaPrint.st
  packages/OmegaPrint-Core.package/CodeHolder.extension/instance/omegaPrintString.st
  packages/OmegaPrint-Core.package/CodeHolder.extension/methodProperties.json
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/KeywordMessageSend.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestUI.class/instance/testOmegaPrintQuint.st
  packages/OmegaPrint-Tests.package/TestUI.class/methodProperties.json
Labels: refactoring

#126 Kommentare eingebunden
  packages/OmegaPrint-Core.package/CodeHolder.extension/instance/toggleOmegaPrint.st
  packages/OmegaPrint-Core.package/CodeHolder.extension/methodProperties.json
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/BlockLiteralNormal.with.and.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestStatements.class/instance/testWithMultipleStatements.st
  packages/OmegaPrint-Tests.package/TestStatements.class/methodProperties.json
Labels: refactoring

#137 Methode um String zu 'umrahmen'
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/BlockLiteralNormal.with.and.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ByteArrayLiteral.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ObjectArrayLiteral.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/include.between.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/join.separatedBy..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/literalArrayWith..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
Labels: refactoring

#139 value Methode in Kategorie evaluation schieben
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/value..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
Labels: refactoring

#151 KeywordMessages (und andere Messages)
  packages/OmegaPrint-Core.package/OPSourceRewriter.class/instance/BinaryMessageSend.with.and..st
  packages/OmegaPrint-Core.package/OPSourceRewriter.class/instance/KeywordMessage.with..st
  packages/OmegaPrint-Core.package/OPSourceRewriter.class/instance/KeywordMessageSend.with.and..st
  packages/OmegaPrint-Core.package/OPSourceRewriter.class/instance/keywordMessageWith.and..st
  packages/OmegaPrint-Core.package/OPSourceRewriter.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestExpression.class/instance/testMultipleSegmentsInCascade.st
  packages/OmegaPrint-Tests.package/TestExpression.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestKeywordMessage.class/README.md
  packages/OmegaPrint-Tests.package/TestKeywordMessage.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestKeywordMessage.class/instance/testWithMultipleSegments.st
  packages/OmegaPrint-Tests.package/TestKeywordMessage.class/instance/testWithSingleSegment.st
  packages/OmegaPrint-Tests.package/TestKeywordMessage.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestKeywordMessage.class/properties.json
  packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testMultipleSegmentsInArgument.st
  packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/instance/testWithReceiverWithSingleSegmentWithComplexArgument.st
  packages/OmegaPrint-Tests.package/TestKeywordMessageSend.class/methodProperties.json
Labels: bug, feature

#154 Dokumentation Readme
  README.md
  screenshots/click_formatting_selection.png
  screenshots/hover_formatting_selection.png
Labels: documentation
