Repository hpi-swa-teaching/OhmPrettyPrint, pull requests merged in 2020-07, with the labels that each got.

#56 Rename OPButton to OPUserInterface
  packages/OmegaPrint-Core.package/OPUserInterface.class/README.md
  packages/OmegaPrint-Core.package/OPUserInterface.class/class/initialize.st
  packages/OmegaPrint-Core.package/OPUserInterface.class/class/isAlreadyInstalled.st
  packages/OmegaPrint-Core.package/OPUserInterface.class/class/omegaPrintQuint.st
  packages/OmegaPrint-Core.package/OPUserInterface.class/methodProperties.json
  packages/OmegaPrint-Core.package/OPUserInterface.class/properties.json
  packages/OmegaPrint-Tests.package/TestUI.class/instance/testOmegaPrintQuint.st
  packages/OmegaPrint-Tests.package/TestUI.class/instance/testRepeatAddButton.st
  packages/OmegaPrint-Tests.package/TestUI.class/methodProperties.json
Labels: refactoring

#61 Refactor OPUserInterface
  packages/OmegaPrint-Core.package/OPUserInterface.class/class/initialize.st
  packages/OmegaPrint-Core.package/OPUserInterface.class/class/isAlreadyInstalled.st
  packages/OmegaPrint-Core.package/OPUserInterface.class/methodProperties.json
Labels: refactoring

#77 leere Bloecke ohne Leerzeichen formatieren
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/BlockLiteralNormal.with.and.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/spaceBeforeCode.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestBlockLiteral.class/instance/testWithoutArgumentsWithoutCode.st
  packages/OmegaPrint-Tests.package/TestBlockLiteral.class/methodProperties.json
Labels: user story

#76 Tests fuer Statements und Zuweisungsoperatoren
  packages/OmegaPrint-Tests.package/TestAssignmentOperation.class/README.md
  packages/OmegaPrint-Tests.package/TestAssignmentOperation.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestAssignmentOperation.class/instance/testWithBindableIdentifierWithAssignmentOperator.st
  packages/OmegaPrint-Tests.package/TestAssignmentOperation.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestAssignmentOperation.class/properties.json
  packages/OmegaPrint-Tests.package/TestStatement.class/README.md
  packages/OmegaPrint-Tests.package/TestStatement.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestStatement.class/instance/testWithMultipleAssignmentOperationsWithExpression.st
  packages/OmegaPrint-Tests.package/TestStatement.class/instance/testWithSingleAssignmentOperationWithExpression.st
  packages/OmegaPrint-Tests.package/TestStatement.class/instance/testWithoutAssignmentOperationWithExpression.st
  packages/OmegaPrint-Tests.package/TestStatement.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestStatement.class/properties.json
Labels: user story

#80 Arrays richtig formatieren
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ByteArrayLiteral.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/LiteralArrayLiteral.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/LiteralArrayLiteralInLiteralArray.with.and.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ObjectArrayLiteral.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ObjectArrayLiteralElementNormal.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/README.md
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/instance/testWithMultipleIntegerLiterals.st
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/instance/testWithSingleIntegerLiteral.st
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/instance/testWithoutIntegerLiteral.st
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestByteArrayLiteral.class/properties.json
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/README.md
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/instance/testWithMultipleLiteralArrayLiteralElements.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/instance/testWithSingleLiteralArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/instance/testWithoutLiteralArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteral.class/properties.json
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/README.md
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/testWithHashWithMultipleLiteralArrayLiteralElements.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/testWithHashWithSingleLiteralArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/testWithHashWithoutLiteralArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/testWithoutHashWithMultipleLiteralArrayLiteralElements.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/testWithoutHashWithSingleLiteralArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/instance/testWithoutHashWithoutLiteralArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestLiteralArrayLiteralInLiteralArray.class/properties.json
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/README.md
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/instance/testWithMultipleObjectArrayLiteralElementsWithPoint.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/instance/testWithMultipleObjectArrayLiteralElementsWithoutPoint.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/instance/testWithSingleObjectArrayLiteralElementWithPoint.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/instance/testWithSingleObjectArrayLiteralElementWithoutPoint.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/instance/testWithoutObjectArrayLiteralElement.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteral.class/properties.json
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteralElement.class/README.md
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteralElement.class/instance/startSymbol.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteralElement.class/instance/testWithStatement.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteralElement.class/instance/testWithStatementWithPoint.st
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteralElement.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestObjectArrayLiteralElement.class/properties.json
Labels: user story

#90 CI nicht mehrfach laufen lassen
  .github/workflows/main.yml
Labels: bug

#89 ExecutableCode besser testen
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ExecutableCode.with.and.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
  packages/OmegaPrint-Tests.package/TestExecutableCode.class/instance/testWithVariablesWithPragmasWithoutCode.st
  packages/OmegaPrint-Tests.package/TestExecutableCode.class/instance/testWithVariablesWithoutPragmasWithoutCode.st
  packages/OmegaPrint-Tests.package/TestExecutableCode.class/instance/testWithoutVariablesWithPragmasWithoutCode.st
  packages/OmegaPrint-Tests.package/TestExecutableCode.class/instance/testWithoutVariablesWithoutPragmasWithoutCode.st
  packages/OmegaPrint-Tests.package/TestExecutableCode.class/methodProperties.json
Labels: bug

#94 Methode für Cascaden geändert
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ExpressionBinaryCascade.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ExpressionOperandCascade.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/ExpressionUnaryCascade.with.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/instance/cascadeWith.and..st
  packages/OmegaPrint-Core.package/OPPrinter.class/methodProperties.json
Labels: refactoring
